# Generated by Django 5.2.15 on 2026-06-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_alter_diaryentry_created_at_alter_event_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary_entries/'),
        ),
    ]
