# Generated by Django 5.2.15 on 2026-06-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0010_tag_diaryentry_tags_task_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='custom_quote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='custom_quote_author',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='diaryentry',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='diary/%Y/%m/'),
        ),
    ]
