# Generated by Django 5.2.15 on 2026-07-02 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0011_add_custom_quote_to_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', '🔐 Login'), ('logout', '🚪 Logout'), ('diary_write', '✍️ Diary Written'), ('diary_edit', '📝 Diary Edited'), ('diary_view', '📖 Diary Viewed'), ('task_view', '✅ Tasks Viewed'), ('task_create', '➕ Task Created'), ('task_complete', '🎯 Task Completed'), ('event_view', '📅 Events Viewed'), ('event_create', '🗓️ Event Created'), ('profile_view', '👤 Profile Viewed'), ('settings_view', '⚙️ Settings Visited')], max_length=30)),
                ('description', models.CharField(max_length=300)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
