# Generated by Django 5.2.15 on 2026-07-02 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0012_systemactivitylog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemactivitylog',
            name='action',
            field=models.CharField(choices=[('login', '🔐 Login'), ('logout', '🚪 Logout'), ('dashboard_view', '📊 Dashboard Viewed'), ('diary_write', '✍️ Diary Written'), ('diary_edit', '📝 Diary Edited'), ('diary_view', '📖 Diary Viewed'), ('diary_delete', '🗑️ Diary Deleted'), ('task_view', '✅ Tasks Viewed'), ('task_create', '➕ Task Created'), ('task_edit', '✏️ Task Updated'), ('task_complete', '🎯 Task Completed'), ('task_delete', '🗑️ Task Deleted'), ('event_view', '📅 Events Viewed'), ('event_create', '🗓️ Event Created'), ('event_edit', '✏️ Event Updated'), ('event_delete', '🗑️ Event Deleted'), ('profile_view', '👤 Profile Viewed'), ('settings_view', '⚙️ Settings Visited')], max_length=30),
        ),
    ]
