# Generated by Django 5.2.15 on 2026-07-02 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0013_add_action_choices_choices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shared_with_email', models.EmailField(db_index=True, max_length=254)),
                ('share_type', models.CharField(choices=[('specific_diary', 'Specific Diary Entry'), ('whole_diary', 'Whole Diary'), ('specific_event', 'Specific Event'), ('whole_events', 'Whole Events')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='diary.diaryentry')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='diary.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares_granted', to=settings.AUTH_USER_MODEL)),
                ('shared_with_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shares_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('owner', 'shared_with_email', 'share_type', 'diary_entry', 'event')},
            },
        ),
    ]
