# Generated by Django 5.2.15 on 2026-07-06 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0015_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='attendance_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('attended', 'Attended'), ('unattended', 'Unattended')], db_index=True, default='pending', max_length=12),
        ),
        migrations.AddField(
            model_name='event',
            name='original_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='original_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
