# Generated by Django 5.2.15 on 2026-07-08 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0016_event_attendance_status_event_original_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharepermission',
            name='share_type',
            field=models.CharField(choices=[('specific_diary', 'Specific Diary Entry'), ('whole_diary', 'Whole Diary'), ('specific_event', 'Specific Event'), ('whole_events', 'Whole Events'), ('whole_tasks', 'Whole Tasks')], max_length=20),
        ),
    ]
