# Generated by Django 5.2.15 on 2026-07-13 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0017_alter_sharepermission_share_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sharepermission',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='sharepermission',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='diary.task'),
        ),
        migrations.AlterField(
            model_name='sharepermission',
            name='share_type',
            field=models.CharField(choices=[('specific_diary', 'Specific Diary Entry'), ('whole_diary', 'Whole Diary'), ('specific_event', 'Specific Event'), ('whole_events', 'Whole Events'), ('whole_tasks', 'Whole Tasks'), ('specific_task', 'Specific Task')], max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='sharepermission',
            unique_together={('owner', 'shared_with_email', 'share_type', 'diary_entry', 'event', 'task')},
        ),
    ]
