# Generated by Django 5.2.15 on 2026-08-14 20:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0018_alter_sharepermission_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="calendar_token",
            field=models.UUIDField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
