# Generated by Django 5.2.15 on 2026-08-14 20:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("diary", "0019_5_fix_calendar_token_duplicates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="calendar_token",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
